### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by chenyongze** [chanyipiaomiao/devops-api#1]
/data/project-coding/go/devops-api (master ✘)✹ ᐅ go build

main.go:4:2: cannot find package "devops-api/common" in any of:
	/usr/local/Cellar/go/1.9.2/libexec/src/devops-api/common (from $GOROOT)
	/Users/*****/go/src/devops-api/common (from $GOPATH)
main.go:5:2: cannot find package "devops-api/routers" in any of:
	/usr/local/Cellar/go/1.9.2/libexec/src/devops-api/routers (from $GOROOT)
	/Users/*****
/go/src/devops-api/routers (from $GOPATH)

**Comment by chanyipiaomiao** [comment]
/data/project-coding/go 这个目录不是在$GOPATH下吧.

**Comment by oldthreefeng** [comment]
@chanyipiaomiao 能否添加一下包管理, 这个方法好像没有了.
common\twostep.go:140:42: otp.Secret undefined (type *twofactor.Totp has no field or method Secret)

**Comment by chanyipiaomiao** [comment]
@oldthreefeng  github.com/sec51/twofactor 这个包安装了吗

**Comment by oldthreefeng** [comment]
![image](https://user-images.githubusercontent.com/38313565/65501963-7d795180-def4-11e9-91ae-61262c9e0f60.png)
安装了的,但是可能版本不对, @chanyipiaomiao

**Comment by chanyipiaomiao** [comment]
@oldthreefeng  我看了下当时我用的commitId是：d22311dbf16eee1f70cf1342345cf36e976a70b7 估计新版本把那个方法给去掉

**Comment by oldthreefeng** [comment]
ok,我去看看这个方法

**Comment by oldthreefeng** [comment]
```
func (otp *Totp) Secret() string {
	return base32.StdEncoding.EncodeToString(otp.key)
}
```
利用了这个方法.他们为什么把这个去掉了啊,  @chanyipiaomiao

**Comment by chanyipiaomiao** [comment]
应该有替代方法吧

**Comment by oldthreefeng** [comment]
> 应该有替代方法吧

我知道了,我的版本低了,我看了是1.0.1版本才支持的,我的是1.0.0,晕了~打扰了~~~
